// src/components/comment/Comment.tsx
import { useState } from 'react';
import { Link } from 'react-router-dom';
import type { Comment as CommentType } from '../../types/comment';
import './Comment.scss';

export default function Comment({ comment }: { comment: CommentType }) {
    const [collapse, setCollapse] = useState(false);
    if (comment.deleted) return <div><div className="deleted-meta"><span className="collapse">[deleted]</span> | Comment Deleted</div></div>;
    return (
        <div>
            <div className={`meta${collapse ? ' meta-collapse' : ''}`}>
                <span className="collapse" onClick={() => setCollapse(!collapse)}>[{collapse ? '+' : '-'}]</span>{' '}
                <Link to={`/user/${comment.user}`}>{comment.user}</Link><span className="time">{comment.time_ago}</span>
            </div>
            <div className="comment-tree"><div hidden={collapse}>
                <p className="comment-text" dangerouslySetInnerHTML={{ __html: comment.content }}></p>
                <ul className="subtree">{comment.comments.map((subComment) => <li key={subComment.id}><Comment comment={subComment} /></li>)}</ul>
            </div></div>
        </div>
    );
}

// src/app/item-details/comment/comment.component.ts
import { Component, Input, OnInit } from '@angular/core';

import { Comment } from '../../shared/models/comment';

@Component({
    selector: 'app-comment',
    templateUrl: './comment.component.html',
    styleUrls: ['./comment.component.scss'],
    standalone: false
})
export class CommentComponent implements OnInit {
  @Input() comment: Comment;
  collapse: boolean;

  constructor() {}

  ngOnInit() {
    this.collapse = false;
  }
}

@if (!comment.deleted) {
  <div>
    <div class="meta" [class.meta-collapse]="collapse">
      <span class="collapse" (click)="collapse = !collapse">[{{collapse ? '+' : '-'}}]</span>
      <a [routerLink]="['/user', comment.user]" routerLinkActive="active">{{comment.user}}</a>
      <span class="time">{{comment.time_ago}}</span>
    </div>
    <div class="comment-tree">
      <div [hidden]="collapse">
        <p class="comment-text" [innerHTML]="comment.content"></p>
        <ul class="subtree">
          @for (subComment of comment.comments; track subComment) {
            <li>
              <app-comment [comment]="subComment"></app-comment>
            </li>
          }
        </ul>
      </div>
    </div>
  </div>
}
@if (comment.deleted) {
  <div>
    <div class="deleted-meta">
      <span class="collapse">[deleted]</span> | Comment Deleted
    </div>
  </div>
}
