// src/app/item-details/item-details.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { Subscription } from 'rxjs';

import { HackerNewsAPIService } from '../shared/services/hackernews-api.service';
import { SettingsService } from '../shared/services/settings.service';

import { Story } from '../shared/models/story';
import { Settings } from '../shared/models/settings';

@Component({
  selector: 'app-item-details',
  templateUrl: './item-details.component.html',
  styleUrls: ['./item-details.component.scss']
})
export class ItemDetailsComponent implements OnInit {
  sub: Subscription;
  item: Story;
  errorMessage = '';
  settings: Settings;

  constructor(
    private _hackerNewsAPIService: HackerNewsAPIService,
    private _settingsService: SettingsService,
    private route: ActivatedRoute,
    private _location: Location
  ) {
    this.settings = this._settingsService.settings;
  }

  ngOnInit() {
    this.sub = this.route.params.subscribe(params => {
      let itemID = +params['id'];
      this._hackerNewsAPIService.fetchItemContent(itemID).subscribe(item => {
        this.item = item;
      }, error => this.errorMessage = 'Could not load item comments.');
    });
    window.scrollTo(0, 0);
  }

  goBack() {
    this._location.back();
  }

  get hasUrl(): boolean {
    return this.item.url.indexOf('http') === 0;
  }

}

<div class="main-content">
  @if (!item && !errorMessage) {
    <app-loader></app-loader>
  }
  @if (!item && errorMessage !== '') {
    <app-error-message [message]="errorMessage"></app-error-message>
  }

  @if (item) {
    <div class="item">
      <div class="mobile item-header">
        <p class="title-block">
          <span class="back-button" (click)="goBack()"></span>
          @if (hasUrl) {
            <a class="title" href="{{item.url}}" [attr.target]="settings.openLinkInNewTab ? '_blank' : null" [attr.rel]="settings.openLinkInNewTab ? 'noopener' : null">
              {{item.title}}
            </a>
          }
          @if (!hasUrl) {
            <a class="title" [routerLink]="['/item', item.id]"
              routerLinkActive="active">
              {{item.title}}
            </a>
          }
        </p>
      </div>
      <div class="laptop" [class.item-header]="item.comments_count > 0 || item.type === 'job'" [class.head-margin]="item.text">
        @if (hasUrl) {
          <p>
            <a class="title" href="{{item.url}}" [attr.target]="settings.openLinkInNewTab ? '_blank' : null" [attr.rel]="settings.openLinkInNewTab ? 'noopener' : null">
              {{item.title}}
            </a>
            @if (item.domain) {
              <span class="domain">({{item.domain}})</span>
            }
          </p>
        }
        @if (!hasUrl) {
          <p>
            <a class="title" [routerLink]="['/item', item.id]" routerLinkActive="active">
              {{item.title}}
            </a>
          </p>
        }
        <div class="subtext">
          @if (item.type !== 'job') {
            <span>
              {{item.points}} points by
              <a [routerLink]="['/user', item.user]" routerLinkActive="active">{{item.user}}</a>
            </span>
          }
          <span [class.item-details]="item.type !== 'job'">
            {{item.time_ago}}
            @if (item.type !== 'job') {
              <span> |
                <a [routerLink]="['/item', item.id]" routerLinkActive="active">
                  {{item.comments_count | comment }}
                </a>
              </span>
            }
          </span>
        </div>
      </div>
      @if (item.type === 'poll') {
        <div class="pollResults">
          @for (pollResult of item.poll; track pollResult) {
            <div class="pollContent">
              <div [innerHTML]="pollResult.content"></div>
              <div class="subtext">{{pollResult.points}} points</div>
              <div class="pollBar" [ngStyle]="{'width': pollResult.points/item.poll_votes_count*100+'%'}"></div>
            </div>
          }
        </div>
      }
      <p class="subject" [innerHTML]="item.content"></p>
      <ul class="comment-list">
        @for (comment of item.comments; track comment) {
          <li >
            <app-comment [comment]="comment"></app-comment>
          </li>
        }
      </ul>
    </div>
  }
</div>

// src/pages/ItemDetails.tsx
import { useCallback, useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { fetchItemContent } from '../api/hnApi';
import Comment from '../components/comment/Comment';
import ErrorMessage from '../components/error-message/ErrorMessage';
import Loader from '../components/loader/Loader';
import { useSettings } from '../context/SettingsContext';
import type { Story } from '../types/story';
import { formatCommentCount } from '../utils/formatCommentCount';
import './ItemDetails.scss';

export default function ItemDetails() {
    const { id } = useParams();
    const navigate = useNavigate();
    const { settings } = useSettings();
    const [item, setItem] = useState<Story | null>(null);
    const [errorMessage, setErrorMessage] = useState('');
    const loadItem = useCallback(() => fetchItemContent(Number(id)), [id]);

    useEffect(() => {
        window.scrollTo(0, 0);
        let cancelled = false;
        setItem(null);
        setErrorMessage('');
        loadItem().then((result) => { if (!cancelled) setItem(result); })
            .catch(() => { if (!cancelled) setErrorMessage('Could not load item comments.'); });
        return () => { cancelled = true; };
    }, [loadItem]);

    const hasUrl = !!item?.url && item.url.indexOf('http') === 0;
    const externalProps = settings.openLinkInNewTab ? { target: '_blank', rel: 'noopener' } : {};
    return <div className="main-content">
        {!item && !errorMessage && <Loader />}
        {!item && errorMessage !== '' && <ErrorMessage message={errorMessage} />}
        {item && <div className="item">
            <div className="mobile item-header"><p className="title-block">
                <span className="back-button" onClick={() => navigate(-1)}></span>
                {hasUrl ? <a className="title" href={item.url} {...externalProps}>{item.title}</a> : <Link className="title" to={`/item/${item.id}`}>{item.title}</Link>}
            </p></div>
            <div className={`laptop${item.comments_count > 0 || item.type === 'job' ? ' item-header' : ''}${item.text ? ' head-margin' : ''}`}>
                {hasUrl ? <p><a className="title" href={item.url} {...externalProps}>{item.title}</a>{item.domain && <span className="domain">({item.domain})</span>}</p>
                    : <p><Link className="title" to={`/item/${item.id}`}>{item.title}</Link></p>}
                <div className="subtext">
                    {item.type !== 'job' && <span>{item.points} points by <Link to={`/user/${item.user}`}>{item.user}</Link></span>}
                    <span className={item.type !== 'job' ? 'item-details' : ''}>{item.time_ago}
                        {item.type !== 'job' && <span> | <Link to={`/item/${item.id}`}>{formatCommentCount(item.comments_count)}</Link></span>}
                    </span>
                </div>
            </div>
            {item.type === 'poll' && <div className="pollResults">
                {item.poll?.map((pollResult, index) => <div key={index} className="pollContent">
                    <div dangerouslySetInnerHTML={{ __html: pollResult.content }}></div>
                    <div className="subtext">{pollResult.points} points</div>
                    <div className="pollBar" style={{ width: `${pollResult.points / (item.poll_votes_count || 1) * 100}%` }}></div>
                </div>)}
            </div>}
            <p className="subject" dangerouslySetInnerHTML={{ __html: item.content ?? '' }}></p>
            <ul className="comment-list">{item.comments?.map((comment) => <li key={comment.id}><Comment comment={comment} /></li>)}</ul>
        </div>}
    </div>;
}
