// src/app/core/header/header.component.ts
import { Component } from '@angular/core';

import { SettingsService } from '../../shared/services/settings.service';
import { Settings } from '../../shared/models/settings';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent {
  settings: Settings;

  constructor(private _settingsService: SettingsService) {
    this.settings = this._settingsService.settings;
  }

  toggleSettings() {
    this._settingsService.toggleSettings();
  }

  scrollTop() {
    window.scrollTo(0, 0);
  }
}

<header>
  <div id="header">
    <a class="home-link" routerLink="/news/1" routerLinkActive="active" (click)="scrollTop()">
      <div class="logo-inner"></div>
      <img class="logo" src="assets/images/logo.svg" alt="Logo">
    </a>
    <div class="header-text">
      <div class="left">
        <span class="header-nav">
          <a routerLink="/newest/1" routerLinkActive="active" (click)="scrollTop()">new</a>
          |
          <a routerLink="/show/1" routerLinkActive="active" (click)="scrollTop()">show</a>
          |
          <a routerLink="/ask/1" routerLinkActive="active" (click)="scrollTop()">ask</a>
          |
          <a routerLink="/jobs/1" routerLinkActive="active" (click)="scrollTop()">jobs</a>
        </span>
      </div>
    </div>
    <div class="info">
      <img class="settings" src="assets/images/cog.svg" alt="Settings" (click)="toggleSettings()">
    </div>
  </div>
  @if (settings.showSettings) {
    <app-settings></app-settings>
  }
</header>

// src/components/header/Header.tsx
import { NavLink } from 'react-router-dom';
import { useSettings } from '../../context/SettingsContext';
import Settings from '../settings/Settings';
import './Header.scss';

export default function Header() {
    const { settings, toggleSettings } = useSettings();
    const scrollTop = () => window.scrollTo(0, 0);
    const navClass = ({ isActive }: { isActive: boolean }) => isActive ? 'active' : '';
    return (
        <header>
            <div id="header">
                <NavLink className={({ isActive }) => `home-link${isActive ? ' active' : ''}`} to="/news/1" onClick={scrollTop}>
                    <div className="logo-inner"></div>
                    <img className="logo" src="/assets/images/logo.svg" alt="Logo" />
                </NavLink>
                <div className="header-text"><div className="left"><span className="header-nav">
                    <NavLink to="/newest/1" className={navClass} onClick={scrollTop}>new</NavLink>{' | '}
                    <NavLink to="/show/1" className={navClass} onClick={scrollTop}>show</NavLink>{' | '}
                    <NavLink to="/ask/1" className={navClass} onClick={scrollTop}>ask</NavLink>{' | '}
                    <NavLink to="/jobs/1" className={navClass} onClick={scrollTop}>jobs</NavLink>
                </span></div></div>
                <div className="info"><img className="settings" src="/assets/images/cog.svg" alt="Settings" onClick={toggleSettings} /></div>
            </div>
            {settings.showSettings && <Settings />}
        </header>
    );
}
