// src/pages/User.tsx
import { useCallback, useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { fetchUser } from '../api/hnApi';
import ErrorMessage from '../components/error-message/ErrorMessage';
import Loader from '../components/loader/Loader';
import type { User as UserType } from '../types/user';
import './User.scss';

export default function User() {
    const { id } = useParams();
    const userID = id ?? '';
    const navigate = useNavigate();
    const [user, setUser] = useState<UserType | null>(null);
    const [errorMessage, setErrorMessage] = useState('');
    const loadUser = useCallback(() => fetchUser(userID), [userID]);
    useEffect(() => {
        let cancelled = false;
        setUser(null); setErrorMessage('');
        loadUser().then((result) => { if (!cancelled) setUser(result); })
            .catch(() => { if (!cancelled) setErrorMessage(`Could not load user ${userID}.`); });
        return () => { cancelled = true; };
    }, [loadUser, userID]);
    return <>
        {!user && !errorMessage && <Loader />}
        {!user && errorMessage !== '' && <ErrorMessage message={errorMessage} />}
        {user && <div className="profile">
            <div className="mobile item-header"><p className="title-block">
                <span className="back-button" onClick={() => navigate(-1)}></span>Profile: {user.id}
            </p></div>
            <div className="main-details"><span className="name">{user.id}</span><span className="right">{user.karma} ★</span>
                <p className="age">Created {user.created}</p></div>
            {user.about && <div className="other-details"><p dangerouslySetInnerHTML={{ __html: user.about }}></p></div>}
        </div>}
    </>;
}

// src/app/user/user.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { Subscription } from 'rxjs';

import { HackerNewsAPIService } from '../shared/services/hackernews-api.service';
import { User } from '../shared/models/user';

@Component({
  selector: 'app-user',
  templateUrl: './user.component.html',
  styleUrls: ['./user.component.scss']
})
export class UserComponent implements OnInit {
  sub: Subscription;
  user: User;
  errorMessage = '';

  constructor(
    private _hackerNewsAPIService: HackerNewsAPIService,
    private route: ActivatedRoute,
    private _location: Location
  ) {}

  ngOnInit() {
    this.sub = this.route.params.subscribe(params => {
      let userID = params['id'];
      this._hackerNewsAPIService.fetchUser(userID).subscribe(data => {
        this.user = data;
      }, error => this.errorMessage = 'Could not load user ' + userID + '.');
    });
  }

  goBack() {
    this._location.back();
  }
}

@if (!user && !errorMessage) {
  <app-loader></app-loader>
}
@if (!user && errorMessage !== '') {
  <app-error-message [message]="errorMessage"></app-error-message>
}

@if (user) {
  <div class="profile">
    <div class="mobile item-header">
      <p class="title-block">
        <span class="back-button" (click)="goBack()"></span>
        Profile: {{ user.id }}
      </p>
    </div>
    <div class="main-details">
      <span class="name">{{ user.id }}</span>
      <span class="right">{{ user.karma }} ★</span>
      <p class="age">Created {{ user.created }}</p>
    </div>
    @if (user.about) {
      <div class="other-details">
        <p [innerHTML]="user.about"></p>
      </div>
    }
  </div>
}
