// src/components/item/Item.tsx
import { Link } from 'react-router-dom';
import { useSettings } from '../../context/SettingsContext';
import type { Story } from '../../types/story';
import { formatCommentCount } from '../../utils/formatCommentCount';
import './Item.scss';

export default function Item({ item, className }: { item: Story; className?: string }) {
    const { settings } = useSettings();
    const hasUrl = !!item.url && item.url.indexOf('http') === 0;
    const titleStyle = { fontSize: `${settings.titleFontSize}px` };
    const externalProps = settings.openLinkInNewTab ? { target: '_blank', rel: 'noopener' } : {};
    return (
        <div className={className} style={{ marginBottom: `${settings.listSpacing}px` }}>
            {hasUrl ? <p><a className="title" style={titleStyle} href={item.url} {...externalProps}>{item.title}</a>
                {item.domain && <span className="domain">({item.domain})</span>}</p>
                : <p><Link className="title" style={titleStyle} to={`/item/${item.id}`}>{item.title}</Link></p>}
            <div className="subtext-palm">
                {item.type !== 'job' && <div className="details"><span className="name"><Link to={`/user/${item.user}`}>{item.user}</Link></span><span className="right">{item.points} ★</span></div>}
                <div className="details">{item.time_ago}{item.type !== 'job' && <Link to={`/item/${item.id}`} className="comment-number"> • {formatCommentCount(item.comments_count)}</Link>}</div>
            </div>
            <div className="subtext-laptop">
                {item.type !== 'job' && <span>{item.points} points by <Link to={`/user/${item.user}`}>{item.user}</Link></span>}
                <span className={item.type !== 'job' ? 'item-details' : ''}>{item.time_ago}
                    {item.type !== 'job' && <span> | <Link to={`/item/${item.id}`}>{formatCommentCount(item.comments_count)}</Link></span>}
                </span>
            </div>
        </div>
    );
}

// src/app/feeds/item/item.component.ts
import { Component, Input } from '@angular/core';
import { Story } from '../../shared/models/story';

import { SettingsService } from '../../shared/services/settings.service';
import { Settings } from '../../shared/models/settings';

@Component({
  // eslint-disable-next-line @angular-eslint/component-selector
  selector: 'item',
  templateUrl: './item.component.html',
  styleUrls: ['./item.component.scss']
})
export class ItemComponent {
  @Input() item: Story;
  settings: Settings;

  constructor(private _settingsService: SettingsService) {
    this.settings = this._settingsService.settings;
  }

  get hasUrl(): boolean {
    return this.item.url.indexOf('http') === 0;
  }

}

<div [ngStyle]="{'margin-bottom': settings.listSpacing+'px'}">
  @if (hasUrl) {
    <p>
      <a class="title" [ngStyle]="{'font-size': settings.titleFontSize+'px'}" href="{{item.url}}" [attr.target]="settings.openLinkInNewTab ? '_blank' : null" [attr.rel]="settings.openLinkInNewTab ? 'noopener' : null">
        {{item.title}}
      </a>
      @if (item.domain) {
        <span class="domain">({{item.domain}})</span>
      }
    </p>
  }
  @if (!hasUrl) {
    <p>
      <a class="title" [ngStyle]="{'font-size': settings.titleFontSize+'px'}" [routerLink]="['/item', item.id]" routerLinkActive="active">
        {{item.title}}
      </a>
    </p>
  }
  <div class="subtext-palm">
    @if (item.type !== 'job') {
      <div class="details">
        <span class="name"><a [routerLink]="['/user', item.user]" routerLinkActive="active">{{item.user}}</a></span>
        <span class="right">{{item.points}} ★</span>
      </div>
    }
    <div class="details">
      {{ item.time_ago }}
      @if (item.type !== 'job') {
        <a [routerLink]="['/item', item.id]" routerLinkActive="active" class="comment-number"> •
          {{item.comments_count | comment }}
        </a>
      }
    </div>
  </div>
  <div class="subtext-laptop">
    @if (item.type !== 'job') {
      <span>
        {{item.points}} points by
        <a [routerLink]="['/user', item.user]" routerLinkActive="active">{{item.user}}</a>
      </span>
    }
    <span [class.item-details]="item.type !== 'job'">
      {{ item.time_ago }}
      @if (item.type !== 'job') {
        <span> |
          <a [routerLink]="['/item', item.id]" routerLinkActive="active">
            {{item.comments_count | comment }}
          </a>
        </span>
      }
    </span>
  </div>
</div>
